### PR TITLE
#74 Adding support for UnLocking and Locking states for Wyze Lock

### PR DESCRIPTION
**Pull request by GuillaumeB-GitHub**
This is to add support for UnLocking and Locking states for Wyze Lock.
I tested locally with my Wyze lock.

### CODE REVIEW

**Comment by lygris** [comment]
will this add in door jammed/left open as well or is it possible to add that?

**Comment by GuillaumeB-GitHub** [comment]
That change doesn't include the support for door jammed/left open.

I looked into it and:
- HA only supports the property is_jammed which means that the lock has stopped working
- From what I can see in the json returned by /openapi/lock/v1/info, Wyze lock doesn't return any information that could be mapped to is_jammed
- Wyze API /openapi/lock/v1/info endpoint provides info regarding the door status, but it doesn't seem to have anything in HA Lock entity to map that.

**Comment by GuillaumeB-GitHub** [comment]
Example of response from /openapi/lock/v1/info endpoint below. If you think we can use something for is_jammed, let me know.

{
  "ReqID": "bc3f443086",
  "ErrNo": 0,
  "ErrMsg": "",
  "device": {
    "uuid": "fb130b12e8901ffe7ecd269bd64d0531",
    "device_type": "102051001000",
    "parent": "8084ebf0af07f9fade5d73e1748b9dc3",
    "hardware_info": {
      "sn": "lkjl0051210403647386",
      "mac": "1C64525DD4DB",
      "cid": "12-34-56-78-90",
      "versions": {
        "app_version": "2.1.22.0",
        "hardware_version": "1.5.0.0",
        "media_version": "0.0.0.0",
        "protocol_version": "0.0.0.6",
        "zigbee_version": "2.0.3.2",
        "fp_version": "0.0.0.0",
        "ble_version": "2.1.22.0"
      }
    },
    "onoff_line": 1,
    "onoff_time": 1692662584551,
    "df": -1,
    "df_refreshtime": -1,
    "power": 11,
    "power_refreshtime": 1692675188944,
    "lqi": 255,
    "lqi_refreshtime": 1692675188944,
    "time": 1685209620817,
    "ctime": 1655608248926,
    "brand": "dding",
    "model": "XNLL901",
    "name": "Ford",
    "nickname": "Wyze Lock",
    "bind_time": 1685209635115,
    "time_zone": -700,
    "dst_offset": 0,
    "locker_status": {
      "door": 4,
      "door_refreshtime": 1692661288674,
      "hardlock": 1,
      "hardlock_refreshtime": 1692675170000
    },
    "door_open_status": 4,
    "door_open_status_time": 1692661288674,
    "calibrate_info": { "status": 1, "stage_time": 1685209694180 },
    "open_volume": 100,
    "open_volume_refreshtime": 1692645312382,
    "auto_lock_time": 0,
    "auto_lock_time_refreshtime": 1692645301832,
    "ajar_alarm": 2,
    "ajar_alarm_refreshtime": 1692645301832,
    "trash_mode": 2,
    "trash_mode_refreshtime": 1692645301832,
    "left_open_time": 0,
    "left_open_time_refreshtime": 1692645301832,
    "keypad_enable_status": 1,
    "keypad_enable_status_refreshtime": 1692645301832,
    "door_sensor": 2,
    "door_sensor_refreshtime": 1692645301832,
    "geo": {
      "lat": "**Sanitized**",
      "lon": "**Sanitized**",
      "radius": 150,
      "address": "**Sanitized**"
    },
    "auto_unlock": 1,
    "notice": { "notice_locked": 1, "notice_unlocked": 2 }
  }
}

**Comment by GuillaumeB-GitHub** [comment]
Hello, would it be possible to add this fix in the next release please ?

**Comment by GuillaumeB-GitHub** [comment]
@SecKatie Hi, iOS it possible to get that PR merged and then release please ?
Thanks

**Comment by SecKatie** [comment]
@GuillaumeB-GitHub How does the `locker_status` change on different states of the door? The number for `door` or `hardlock` might have that information.

```
"locker_status": {
  "door": 4,
  "door_refreshtime": 1692661288674,
  "hardlock": 1,
  "hardlock_refreshtime": 1692675170000
}
```

**Comment by GuillaumeB-GitHub** [comment]
> @GuillaumeB-GitHub How does the `locker_status` change on different states of the door? The number for `door` or `hardlock` might have that information.
> 
> ```
> "locker_status": {
>   "door": 4,
>   "door_refreshtime": 1692661288674,
>   "hardlock": 1,
>   "hardlock_refreshtime": 1692675170000
> }
> ```

"The number for door or hardlock might have that information.'  -> what information are you talking about ?

**Review by SecKatie — APPROVED** [review]
LGTM. Thank you for the contribution. I am sorry for the great delay in getting to this. I am trying to carve out more time for this project in the future.

**Comment by GuillaumeB-GitHub** [comment]
Thank you !

**Pull request merged**
